# Note: this docker-compose file is used to build/run the project _locally_
# Separate configuration is used when deploying to AWS.

version: "3.3"
volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-data:/data/db
  mongodb-express:
    image: mongo-express
    container_name: mongoexpress
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=example
    ports:
      - 8081:8081
    depends_on:
      - mongodb
  duguo-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: duguo-app
    depends_on:
      - duguo-tokenizer
    ports:
      - 0.0.0.0:8000:8000 # Needs to be non-localhost binding for Windows/Mac. See: https://github.com/docker/for-win/issues/197
    # volumes:
    #   - ~/GitHub/DuGuo-Chinese-Reading-App/app:/app